# Generated by Django 2.2.3 on 2019-09-29 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('token_books', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
    ]
