# Generated by Django 2.2.3 on 2019-11-27 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0005_bookissue'),
        ('lms', '0005_auto_20191126_1824'),
    ]

    operations = [
    ]
